# Generated by Django 4.2.5 on 2023-10-19 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media/places')),
                ('top_deal', models.BooleanField(default=False)),
                ('age', models.IntegerField()),
                ('duration', models.CharField(max_length=30)),
                ('Start_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TripTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('setDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacesRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')])),
                ('rating_date', models.DateTimeField(auto_now_add=True)),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('places', 'user')},
            },
        ),
    ]
