# Generated by Django 4.2.5 on 2023-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_image_place_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptracker',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
