# Generated by Django 4.2.5 on 2023-10-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/hotels'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/hotels'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/hotels'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/hotels'),
        ),
    ]
