# Generated by Django 4.2.5 on 2023-10-17 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_image_hotel_image1_hotel_image2_hotel_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreservation',
            name='hotels',
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='hotel_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
