# Generated by Django 4.2.5 on 2023-10-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=50)),
                ('res_type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/restaurant')),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('open_at', models.TimeField()),
                ('close_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/items')),
                ('description', models.TextField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantmodel')),
            ],
        ),
    ]
