# Generated by Django 4.2.5 on 2023-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='close_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='restaurantmodel',
            name='open_at',
            field=models.TimeField(),
        ),
    ]
