# Generated by Django 4.2.5 on 2023-10-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurantmodel_close_at_and_more'),
        ('restaurant', '0002_foodorder'),
    ]

    operations = [
    ]
